//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormProject.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Form Template.
        /// </summary>
        public static string CreateFormTemplate {
            get {
                return ResourceManager.GetString("CreateFormTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Process.
        /// </summary>
        public static string CreateProcess {
            get {
                return ResourceManager.GetString("CreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Dept {
            get {
                return ResourceManager.GetString("Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        public static string Doc_Name {
            get {
                return ResourceManager.GetString("Doc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No.
        /// </summary>
        public static string Doc_No {
            get {
                return ResourceManager.GetString("Doc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string Doc_Type {
            get {
                return ResourceManager.GetString("Doc_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doccument( If have).
        /// </summary>
        public static string Doccument {
            get {
                return ResourceManager.GetString("Doccument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong!.
        /// </summary>
        public static string Error_Common {
            get {
                return ResourceManager.GetString("Error_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not enough or format incorrect!.
        /// </summary>
        public static string Error_Lack_Info {
            get {
                return ResourceManager.GetString("Error_Lack_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select who action next step!.
        /// </summary>
        public static string Error_NeedSelectNextActionBy {
            get {
                return ResourceManager.GetString("Error_NeedSelectNextActionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exist user who action next step!.
        /// </summary>
        public static string Error_NotExistUser {
            get {
                return ResourceManager.GetString("Error_NotExistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notice failed!.
        /// </summary>
        public static string Error_Send_Notice {
            get {
                return ResourceManager.GetString("Error_Send_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exist!.
        /// </summary>
        public static string Error_User_Not_Exist {
            get {
                return ResourceManager.GetString("Error_User_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis factor.
        /// </summary>
        public static string Field_Analysis_factor {
            get {
                return ResourceManager.GetString("Field_Analysis_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify 4M.
        /// </summary>
        public static string Field_Classify4M {
            get {
                return ResourceManager.GetString("Field_Classify4M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do Reject.
        /// </summary>
        public static string Field_Comment_reject {
            get {
                return ResourceManager.GetString("Field_Comment_reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm artifact.
        /// </summary>
        public static string Field_Confirm_artifact {
            get {
                return ResourceManager.GetString("Field_Confirm_artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm factor.
        /// </summary>
        public static string Field_Confirm_factor {
            get {
                return ResourceManager.GetString("Field_Confirm_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create by.
        /// </summary>
        public static string Field_Create_by {
            get {
                return ResourceManager.GetString("Field_Create_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date.
        /// </summary>
        public static string Field_Create_date {
            get {
                return ResourceManager.GetString("Field_Create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Field_Customer {
            get {
                return ResourceManager.GetString("Field_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date make.
        /// </summary>
        public static string Field_Date_make {
            get {
                return ResourceManager.GetString("Field_Date_make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Field_Draft {
            get {
                return ResourceManager.GetString("Field_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string Field_Due_date {
            get {
                return ResourceManager.GetString("Field_Due_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group model.
        /// </summary>
        public static string Field_Group_Model {
            get {
                return ResourceManager.GetString("Field_Group_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image NG.
        /// </summary>
        public static string Field_Image_NG {
            get {
                return ResourceManager.GetString("Field_Image_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Field_Model {
            get {
                return ResourceManager.GetString("Field_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modify by.
        /// </summary>
        public static string Field_Modify_by {
            get {
                return ResourceManager.GetString("Field_Modify_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modify time.
        /// </summary>
        public static string Field_Modify_date {
            get {
                return ResourceManager.GetString("Field_Modify_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control number.
        /// </summary>
        public static string Field_No {
            get {
                return ResourceManager.GetString("Field_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number NG.
        /// </summary>
        public static string Field_Number_NG {
            get {
                return ResourceManager.GetString("Field_Number_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number test.
        /// </summary>
        public static string Field_Number_test {
            get {
                return ResourceManager.GetString("Field_Number_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occur content.
        /// </summary>
        public static string Field_Occur_content {
            get {
                return ResourceManager.GetString("Field_Occur_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occur date.
        /// </summary>
        public static string Field_Occur_date {
            get {
                return ResourceManager.GetString("Field_Occur_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occur frequency.
        /// </summary>
        public static string Field_Occur_frequency {
            get {
                return ResourceManager.GetString("Field_Occur_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occur place.
        /// </summary>
        public static string Field_Occur_place {
            get {
                return ResourceManager.GetString("Field_Occur_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person detect.
        /// </summary>
        public static string Field_Person_detect {
            get {
                return ResourceManager.GetString("Field_Person_detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point change.
        /// </summary>
        public static string Field_Point_change {
            get {
                return ResourceManager.GetString("Field_Point_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason error.
        /// </summary>
        public static string Field_Reason_error {
            get {
                return ResourceManager.GetString("Field_Reason_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason occur.
        /// </summary>
        public static string Field_Reason_occur {
            get {
                return ResourceManager.GetString("Field_Reason_occur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response occur place.
        /// </summary>
        public static string Field_Response_occur_place {
            get {
                return ResourceManager.GetString("Field_Response_occur_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retest.
        /// </summary>
        public static string Field_Retest {
            get {
                return ResourceManager.GetString("Field_Retest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Field_Status {
            get {
                return ResourceManager.GetString("Field_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step error.
        /// </summary>
        public static string Field_Step_error {
            get {
                return ResourceManager.GetString("Field_Step_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step occur.
        /// </summary>
        public static string Field_Step_occur {
            get {
                return ResourceManager.GetString("Field_Step_occur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy follow.
        /// </summary>
        public static string Field_Strategy_follow {
            get {
                return ResourceManager.GetString("Field_Strategy_follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy IsPokayoke.
        /// </summary>
        public static string Field_Strategy_IsPokayoke {
            get {
                return ResourceManager.GetString("Field_Strategy_IsPokayoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy longtime.
        /// </summary>
        public static string Field_Strategy_longtime {
            get {
                return ResourceManager.GetString("Field_Strategy_longtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy temp.
        /// </summary>
        public static string Field_Strategy_temp {
            get {
                return ResourceManager.GetString("Field_Strategy_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Field_Subject {
            get {
                return ResourceManager.GetString("Field_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify Claim.
        /// </summary>
        public static string Field_Type {
            get {
                return ResourceManager.GetString("Field_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Type.
        /// </summary>
        public static string Field_Type_Form {
            get {
                return ResourceManager.GetString("Field_Type_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người báo cáo bởi/ 報告部.
        /// </summary>
        public static string Form_BaoCao {
            get {
                return ResourceManager.GetString("Form_BaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng bộ phận chất lượng phê duyệt/ QAマネージャ承認.
        /// </summary>
        public static string Form_Complete {
            get {
                return ResourceManager.GetString("Form_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát hành bởi/ 発行部.
        /// </summary>
        public static string Form_PhatHanh {
            get {
                return ResourceManager.GetString("Form_PhatHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA xác nhận/ QA確認.
        /// </summary>
        public static string Form_QAXacNhan {
            get {
                return ResourceManager.GetString("Form_QAXacNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng bộ phận phát sinh phê duyệt/ 発生部のマネージャ承認.
        /// </summary>
        public static string Form_TruongBP {
            get {
                return ResourceManager.GetString("Form_TruongBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time.
        /// </summary>
        public static string Frequence_occur_First {
            get {
                return ResourceManager.GetString("Frequence_occur_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recur.
        /// </summary>
        public static string Frequence_occur_recur {
            get {
                return ResourceManager.GetString("Frequence_occur_recur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Select Image NG.
        /// </summary>
        public static string Image_NG_AttachRequired {
            get {
                return ResourceManager.GetString("Image_NG_AttachRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Image NG.
        /// </summary>
        public static string Image_NGRequired {
            get {
                return ResourceManager.GetString("Image_NGRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infact.
        /// </summary>
        public static string Infact {
            get {
                return ResourceManager.GetString("Infact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is apply  Pokayoke.
        /// </summary>
        public static string Label_IsPokayok {
            get {
                return ResourceManager.GetString("Label_IsPokayok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Claim.
        /// </summary>
        public static string MyClaim {
            get {
                return ResourceManager.GetString("MyClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Just send you a request No {1}!.
        /// </summary>
        public static string Notice_Approve {
            get {
                return ResourceManager.GetString("Notice_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just created successfully Claim {0}.
        /// </summary>
        public static string Notice_Create_Claim {
            get {
                return ResourceManager.GetString("Notice_Create_Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just modified successfully Claim {0}.
        /// </summary>
        public static string Notice_Modify_Claim {
            get {
                return ResourceManager.GetString("Notice_Modify_Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Just reject your request No {1}!.
        /// </summary>
        public static string Notice_Reject {
            get {
                return ResourceManager.GetString("Notice_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occur.
        /// </summary>
        public static string Occur {
            get {
                return ResourceManager.GetString("Occur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC.
        /// </summary>
        public static string PIC {
            get {
                return ResourceManager.GetString("PIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter No!.
        /// </summary>
        public static string Re {
            get {
                return ResourceManager.GetString("Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why you reject?.
        /// </summary>
        public static string Reason_Reject {
            get {
                return ResourceManager.GetString("Reason_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập phân tích các yếu tố phát sinh.
        /// </summary>
        public static string Require_Analysis_factor {
            get {
                return ResourceManager.GetString("Require_Analysis_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập xác nhận hiện vật.
        /// </summary>
        public static string Require_Confirm_artifact {
            get {
                return ResourceManager.GetString("Require_Confirm_artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập xác định yếu tố phát sinh.
        /// </summary>
        public static string Require_Confirm_factor {
            get {
                return ResourceManager.GetString("Require_Confirm_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập ngày lập.
        /// </summary>
        public static string Require_Create_date {
            get {
                return ResourceManager.GetString("Require_Create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập khách hàng.
        /// </summary>
        public static string Require_Customer {
            get {
                return ResourceManager.GetString("Require_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập ngày sản xuất.
        /// </summary>
        public static string Require_Date_make {
            get {
                return ResourceManager.GetString("Require_Date_make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập nhóm linh kiện.
        /// </summary>
        public static string Require_Model_group {
            get {
                return ResourceManager.GetString("Require_Model_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập tên linh kiện.
        /// </summary>
        public static string Require_Model_name {
            get {
                return ResourceManager.GetString("Require_Model_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập mã quản lý.
        /// </summary>
        public static string Require_No {
            get {
                return ResourceManager.GetString("Require_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập số lượng NG.
        /// </summary>
        public static string Require_Number_NG {
            get {
                return ResourceManager.GetString("Require_Number_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập số lượng kiểm tra.
        /// </summary>
        public static string Require_Number_test {
            get {
                return ResourceManager.GetString("Require_Number_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập nội dung phát sinh.
        /// </summary>
        public static string Require_Occur_content {
            get {
                return ResourceManager.GetString("Require_Occur_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập ngày giờ phát sinh.
        /// </summary>
        public static string Require_Occur_date {
            get {
                return ResourceManager.GetString("Require_Occur_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập tần xuất phát sinh.
        /// </summary>
        public static string Require_Occur_frequency {
            get {
                return ResourceManager.GetString("Require_Occur_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập địa điểm phát sinh.
        /// </summary>
        public static string Require_Occur_place {
            get {
                return ResourceManager.GetString("Require_Occur_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập người phát hiện.
        /// </summary>
        public static string Require_Person_detect {
            get {
                return ResourceManager.GetString("Require_Person_detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập điều tra điểm thay đổi.
        /// </summary>
        public static string Require_Point_change {
            get {
                return ResourceManager.GetString("Require_Point_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập tái thử nghiệm.
        /// </summary>
        public static string Require_Retest {
            get {
                return ResourceManager.GetString("Require_Retest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập chủ đề.
        /// </summary>
        public static string Require_Subject {
            get {
                return ResourceManager.GetString("Require_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần nhập loại claim.
        /// </summary>
        public static string Require_Type {
            get {
                return ResourceManager.GetString("Require_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select step to reject.
        /// </summary>
        public static string Select_Step_To_Reject {
            get {
                return ResourceManager.GetString("Select_Step_To_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff code.
        /// </summary>
        public static string StaffCode {
            get {
                return ResourceManager.GetString("StaffCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Information.
        /// </summary>
        public static string Summary_Information {
            get {
                return ResourceManager.GetString("Summary_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary measures.
        /// </summary>
        public static string Title__Temporary_measures {
            get {
                return ResourceManager.GetString("Title_ Temporary_measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of occurrence investigation.
        /// </summary>
        public static string Title_Cause_occur {
            get {
                return ResourceManager.GetString("Title_Cause_occur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of outflow investigation.
        /// </summary>
        public static string Title_Cause_outflow {
            get {
                return ResourceManager.GetString("Title_Cause_outflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Info Claim.
        /// </summary>
        public static string Title_Common_Info {
            get {
                return ResourceManager.GetString("Title_Common_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containment Actions.
        /// </summary>
        public static string Title_Containment_action {
            get {
                return ResourceManager.GetString("Title_Containment_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation of delivery history.
        /// </summary>
        public static string Title_Delivery_history {
            get {
                return ResourceManager.GetString("Title_Delivery_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ①Occur status (phenomenon - Content - Arise Quantitis - Treatment).
        /// </summary>
        public static string Title_Occur_Status {
            get {
                return ResourceManager.GetString("Title_Occur_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outflow countermeasures.
        /// </summary>
        public static string Title_Outflow_countermeasures {
            get {
                return ResourceManager.GetString("Title_Outflow_countermeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Corrective Action &amp; Action Taken to Prevent Recurrence.
        /// </summary>
        public static string Title_Permanent_Corrective__Action {
            get {
                return ResourceManager.GetString("Title_Permanent_Corrective_ Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response For occur place.
        /// </summary>
        public static string Title_Response_Occur_place {
            get {
                return ResourceManager.GetString("Title_Response_Occur_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of check.
        /// </summary>
        public static string Title_result_check {
            get {
                return ResourceManager.GetString("Title_result_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Cause.
        /// </summary>
        public static string Title_Root_Cause {
            get {
                return ResourceManager.GetString("Title_Root_Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock check method and result.
        /// </summary>
        public static string Title_Stock_check_method {
            get {
                return ResourceManager.GetString("Title_Stock_check_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ④ Appropriate booklet （Content of the book ・ Estimated effectiveness）.
        /// </summary>
        public static string Title_Strategy {
            get {
                return ResourceManager.GetString("Title_Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⑤Strategy follow (Deploying to another model ・ customer stages ・  other factories).
        /// </summary>
        public static string Title_Strategy_follow {
            get {
                return ResourceManager.GetString("Title_Strategy_follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targetted Part No.
        /// </summary>
        public static string Title_Target_part_no {
            get {
                return ResourceManager.GetString("Title_Target_part_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing causes  （Machine-generated problems ・ re-testing ・ analyzing why）.
        /// </summary>
        public static string Title_Trace_Reason {
            get {
                return ResourceManager.GetString("Title_Trace_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ②Understand Issus ( Result of Confirm Model, Analysis Reason, Status Processing).
        /// </summary>
        public static string Title_Understand_Issus {
            get {
                return ResourceManager.GetString("Title_Understand_Issus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnomal Quality.
        /// </summary>
        public static string Type_abnormal {
            get {
                return ResourceManager.GetString("Type_abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform.
        /// </summary>
        public static string Type_Normal {
            get {
                return ResourceManager.GetString("Type_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string Type_Serious {
            get {
                return ResourceManager.GetString("Type_Serious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Setting.
        /// </summary>
        public static string UserSetting {
            get {
                return ResourceManager.GetString("UserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim đang chờ tôi.
        /// </summary>
        public static string WattingMe {
            get {
                return ResourceManager.GetString("WattingMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
