//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewestClaim
    {
        public Nullable<long> RowNumber { get; set; }
        public int Id { get; set; }
        public string No { get; set; }
        public string Subject { get; set; }
        public string Customer { get; set; }
        public string Model_name { get; set; }
        public string Model_group { get; set; }
        public string Model_Id { get; set; }
        public string Create_by { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Type { get; set; }
        public string Occur_content { get; set; }
        public Nullable<System.DateTime> Occur_date { get; set; }
        public string Image_NG { get; set; }
        public string Occur_place { get; set; }
        public string Person_detect { get; set; }
        public Nullable<int> Number_NG { get; set; }
        public Nullable<int> Number_test { get; set; }
        public string Occur_frequency { get; set; }
        public Nullable<System.DateTime> Date_make { get; set; }
        public string Confirm_artifact { get; set; }
        public string Point_change { get; set; }
        public string Retest { get; set; }
        public string Confirm_factor { get; set; }
        public string Analysis_factor { get; set; }
        public string Reason_occur { get; set; }
        public string Reason_error { get; set; }
        public string Step_occur { get; set; }
        public string Step_error { get; set; }
        public Nullable<int> Strategy_IsPokayoke { get; set; }
        public string Strategy_temp { get; set; }
        public string Strategy_longtime { get; set; }
        public string Strategy_follow { get; set; }
        public string Strategy_verify { get; set; }
        public string Response_occur_place { get; set; }
        public string Confirm_complete { get; set; }
        public Nullable<int> Status_approval { get; set; }
        public Nullable<int> IsNewest { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ProcessListId { get; set; }
        public string Process { get; set; }
        public string Modify_by { get; set; }
        public Nullable<System.DateTime> Modify_date { get; set; }
        public string Comment_reject { get; set; }
        public string ActionName { get; set; }
        public string Next_Action_by { get; set; }
        public Nullable<int> CanEdit { get; set; }
        public string Classify4M { get; set; }
        public Nullable<System.DateTime> Due_date { get; set; }
        public string FileAttach { get; set; }

    }
}
